name: Build and Release
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag name'     
        required: true
      note:
        description: 'Release note'
        
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Build
        run: |
          npm i -g @vercel/ncc
          npm i @actions/github
          npm run build
      - name: Commit and Push
        run: |
          git config --global user.name '${{ github.actor }}'
          git config --global user.email '${{ github.actor }}@gmail.com'
          git pull origin master
          git add .
          git commit -m "dist build"
          git push origin master

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Test index.js
        env:
          INPUT_GITHUB_USERNAME: "${{ github.actor }}"
          INPUT_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          INPUT_TARGET_REPOS: '[${{ github.repository }}]'
          INPUT_OUTPUT_STYLE: MARKDOWN
          INPUT_IGNORE_EVENTS: '[]'
          INPUT_README_PATH: README.md
          INPUT_COMMIT_MESSAGE: Update README.md
          INPUT_EVENT_LIMIT: '100'
        run: node ./dist/index.js

  release:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Pull latest
        run: |
          git config --global user.name '${{ github.actor }}'
          git config --global user.email '${{ github.actor }}@gmail.com'
          git pull origin master
      - name: Tag it
        run: |
          git tag -a ${{ inputs.tag }} -m "${{ inputs.note }}" master
          git push origin ${{ inputs.tag }}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ inputs.tag }}
          name: Release ${{ inputs.tag }}
          body: ${{ inputs.note }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_TEST }}
